version: "3.7"

services:
  db:
    image: postgres:15
    ports:
      - "9432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres

volumes:
  postgres-volume:
