version: "3.7"

services:
  db:
    image: postgres:15
    ports:
      - "9432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres
    networks:
      - actual-mlops

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: db
    depends_on:
      - db
    networks:
      - actual-mlops

volumes:
  postgres-volume:

networks:
  actual-mlops:
    driver: bridge
