# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Data Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}


jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Collect Repositories
      run: |
        python -m src.engineering.github.collector \
        collect-repository -o apache -r kafka

    - name: Collect Commits
      run: |
        python -m src.engineering.github.collector \
        collect-commits -o apache -r kafka

    - name: DVC
      run: |
        dvc add src/engineering/github/data/
        dvc push

    - name: Push updated dvc files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add '**/*.dvc'
        git commit -am "Automated dvc amend"
        git push
