name: Validate Commits

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:

  pipeline:

    runs-on: self-hosted
    if: startsWith(github.head_ref, 'ETL/commits/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pull files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc pull -r commits

      - name: Validate
        run: |
          dvc diff --json ${{github.base_ref}} ${{github.ref}} \
            | jq -r '.added[].path, .modified[].path, .deleted[].path, .renamed[].path' \
            | grep ".json$" \
            | xargs python -m src.quality.commits validate-files --files

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GA_TOKEN }}"
          MERGE_DELETE_BRANCH: true
